---
title: "Characteristics_of_HTCs"
author: "Jesse Warren"
date: "4/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
library(xlsx)
library(ggpubr)
options(tigris_use_cache = TRUE)
```




```{r Load ACS variables used as proxy measures of HTC communities, cache=TRUE}
#WA HTC community list from Census Bureau:
  # Recent Immigrants
  # Refugees
  # Rural
  # Homeless
  # Anti-government 
  # Seniors
  # African-American
  # American Indian/Alaska Native
  # Asian-American (Chinese)
  # Asian-American (Filipino)
  # Asian-American (Indian/Sub Continent)
  # Asian-American (Korean)
  # Asian-American (Vietnamese)
  # Children (younger than 5)
  # Disabled
  # College Students
  # Faith-Based Community
  # Hispanic/ Latino
  # Renters/Highly Mobile
  # LGBTQ
  # Middle-eastern North African MENA
  # Migrant Workers
  # Military/ Veterans
  # Pacific Islander
  # Russian 

#load ACS census variables
#load variable list
vlist <- load_variables(2018, "acs5", cache = TRUE)

#list of variables
ACS_2018_proxy_variables <- c(total_pop = "B01001_001",
                              unweighted_sample_count_of_pop = "B00001_001",
                              foreign_born_entered_US_after_2010 = "B05005_004",
                              age_65_to_66_female = "B01001_044",
                              age_67_to_69_female = "B01001_045",
                              age_70_to_74_female = "B01001_046",
                              age_75_to_79_female = "B01001_047",
                              age_80_to_84_female = "B01001_048",
                              age_85_plus_female = "B01001_049",
                              age_65_to_66_male = "B01001_020",
                              age_67_to_69_male = "B01001_021",
                              age_70_to_74_male = "B01001_022",
                              age_75_to_79_male = "B01001_023",
                              age_80_to_84_male = "B01001_024",
                              age_85_plus_male = "B01001_025",
                              black_or_african_american = "B01001B_001",
                              american_indian_and_alaska_native = "B01001C_001",
                              asian_american_chinese_alone = "B02015_007",
                              asian_american_taiwanese_alone = "B02015_020",
                              asian_american_filipino_alone = "B02015_008",
                              asian_american_indian_and_subcontinent_alone = "B02015_002",
                              asian_american_korean_alone = "B02015_012",
                              asian_american_vietnamese_alone = "B02015_022",
                              age_under_5_female = "B01001_027",
                              age_under_5_male = "B01001_003",
                              disability_under_5_male = "B18101_004",
                              disability_5_to_17_male = "B18101_007",
                              disability_18_to_34_male = "B18101_010",
                              disability_35_to_64_male = "B18101_013",
                              disability_65_to_74_male = "B18101_016",
                              disability_75_plus_male = "B18101_019",
                              disability_under_5_female = "B18101_023",
                              disability_5_to_17_female = "B18101_026",
                              disability_18_to_34_female = "B18101_029",
                              disability_35_to_64_female = "B18101_032",
                              disability_65_to_74_female = "B18101_035",
                              disability_75_plus_female = "B18101_038",
                              enrolled_public_college_or_grad_school_male = "B14004_003",
                              enrolled_private_college_or_grad_school_male = "B14004_008",
                              enrolled_public_college_or_grad_school_female = "B14004_019",
                              enrolled_private_college_or_grad_school_female = "B14004_024",
                              hispanic_or_latino = "B03001_003",
                              renters = "B25026_009",
                              MENA_northern_africa = "B05006_101",
                              MENA_jordan = "B05006_081",
                              MENA_kuwait = "B05006_082",
                              MENA_lebanon = "B05006_083",
                              MENA_saudi_arabia = "B05006_084",
                              MENA_syria = "B05006_085",
                              MENA_yemen = "B05006_086",
                              MENA_iran = "B05006_060",
                              MENA_iraq = "B05006_079",
                              vacant_housing_for_migrant_workers = "B25004_007",
                              veterans_age_18_to_64 = "C21007_003",
                              veterans_age_64_plus = "C21007_018",
                              native_hawaiian_or_API_alone = "B02001_006",
                              russian_ancestry = "B04006_064"
                              )


#load ACS census tract data
ACS_2018_variables_tract_raw <- get_acs(geography = "tract",
                             variables = ACS_2018_proxy_variables,
                             state = "WA",
                             year = 2018,
                             geometry = TRUE,
                             output = "wide")

#load ACS county data
ACS_2018_variables_county_raw <- get_acs(geography = "county",
                             variables = ACS_2018_proxy_variables,
                             state = "WA",
                             year = 2018,
                             geometry = TRUE,
                             output = "wide")

```


```{r Clean ACS data}

#rowmeans function to create average margin of errors
my_rowmeans = function(...) Reduce(`+`, list(...))/length(list(...))

#create function to combine variables to create single metrics for each HTC, drop unnecessary variables
combine_ACS_variables_function <- function(df) {
  df %>% 
    #combine variables to get single variable for each HTC
    mutate(seniorsE = age_65_to_66_femaleE +
                    age_67_to_69_femaleE +
                    age_70_to_74_femaleE +
                    age_75_to_79_femaleE +
                    age_80_to_84_femaleE +
                    age_85_plus_femaleE +
                    age_65_to_66_maleE +
                    age_67_to_69_maleE +
                    age_70_to_74_maleE +
                    age_75_to_79_maleE +
                    age_80_to_84_maleE +
                    age_85_plus_maleE,
         seniorsM = my_rowmeans(age_65_to_66_femaleM,
                             age_67_to_69_femaleM),
         children_under_5E = age_under_5_femaleE +
                            age_under_5_maleE,
         children_under_5M = my_rowmeans(age_under_5_femaleM,
                                          age_under_5_maleM),
         asian_american_chinese_or_taiwanese_aloneE = asian_american_chinese_aloneE +
                                                      asian_american_taiwanese_aloneE,
         asian_american_chinese_or_taiwanese_aloneM = my_rowmeans(asian_american_chinese_aloneM,
                                                      asian_american_taiwanese_aloneM),
         have_disabilityE = disability_under_5_maleE +
                       disability_5_to_17_maleE +
                       disability_18_to_34_maleE +
                       disability_35_to_64_maleE +
                       disability_65_to_74_maleE +
                       disability_75_plus_maleE +
                       disability_under_5_femaleE +
                       disability_5_to_17_femaleE +
                       disability_18_to_34_femaleE +
                       disability_35_to_64_femaleE +
                       disability_65_to_74_femaleE +
                       disability_75_plus_femaleE,
          have_disabilityM = my_rowmeans(disability_under_5_maleM,
                                    disability_5_to_17_maleM,
                                    disability_18_to_34_maleM,
                                    disability_35_to_64_maleM,
                                    disability_65_to_74_maleM,
                                    disability_75_plus_maleM,
                                    disability_under_5_femaleM,
                                    disability_5_to_17_femaleM,
                                    disability_18_to_34_femaleM,
                                    disability_35_to_64_femaleM,
                                    disability_65_to_74_femaleM,
                                    disability_75_plus_femaleM),
         college_studentsE = enrolled_public_college_or_grad_school_maleE +
                             enrolled_private_college_or_grad_school_maleE +
                             enrolled_public_college_or_grad_school_femaleE +
                             enrolled_private_college_or_grad_school_femaleE,
         college_studentsM = my_rowmeans(enrolled_public_college_or_grad_school_maleM,
                                         enrolled_private_college_or_grad_school_maleM,
                                         enrolled_public_college_or_grad_school_femaleM,
                                         enrolled_private_college_or_grad_school_femaleM),
         MENA_originE =  MENA_northern_africaE +
                              MENA_jordanE +
                              MENA_kuwaitE +
                              MENA_lebanonE +
                              MENA_saudi_arabiaE +
                              MENA_syriaE +
                              MENA_yemenE +
                              MENA_iranE +
                              MENA_iraqE,
         MENA_originM = my_rowmeans(MENA_northern_africaM,
                              MENA_jordanM,
                              MENA_kuwaitM,
                              MENA_lebanonM,
                              MENA_saudi_arabiaM,
                              MENA_syriaM,
                              MENA_yemenM,
                              MENA_iranM,
                              MENA_iraqM),
         veteran_statusE = veterans_age_18_to_64E +
                     veterans_age_64_plusE,
         veteran_statusM = my_rowmeans(veterans_age_18_to_64M,
                     veterans_age_64_plusM)
  )
}


#run variable combination function over tracts and counties
ACS_2018_variables_tract_clean <- ACS_2018_variables_tract_raw
ACS_2018_variables_tract_clean <- combine_ACS_variables_function(ACS_2018_variables_tract_clean)

ACS_2018_variables_county_clean <- ACS_2018_variables_county_raw
ACS_2018_variables_county_clean <- combine_ACS_variables_function(ACS_2018_variables_county_clean)


#create function to select only necessary variables
select_relevant_ACS_variables_function <- function(df) {
  df %>% 
    select(GEOID,
           NAME,
           starts_with("total_pop"),
           unweighted_sample_count_of_popE,
           starts_with("foreign_born_entered_US_after_2010"),
           starts_with("seniors"),
           starts_with("black_or_african_american"),
           starts_with("american_indian_and_alaska_native"),
           starts_with("asian_american_chinese_or_taiwanese_alone"),
           starts_with("asian_american_filipino_alone"),
           starts_with("asian_american_indian_and_subcontinent_alone"),
           starts_with("asian_american_korean_alone"),
           starts_with("asian_american_vietnamese_alone"),
           starts_with("children_under_5"),
           starts_with("have_disability"),
           starts_with("college_students"),
           starts_with("hispanic_or_latino"),
           starts_with("renters"),
           starts_with("MENA_origin"),
           starts_with("vacant_housing_for_migrant_workers"),
           starts_with("veteran_status"),
           starts_with("native_hawaiian_or_API_alone"),
           starts_with("russian_ancestry")
          )
}

#run variable selection function over tracts and counties
ACS_2018_variables_tract_clean <- select_relevant_ACS_variables_function(ACS_2018_variables_tract_clean)
ACS_2018_variables_county_clean <- select_relevant_ACS_variables_function(ACS_2018_variables_county_clean) %>% 
  select(-total_popM) #remove margin of error for total population because it doesnt exist for counties


```


```{r Aggregate HTCs}
#This code creates a column of sum of all HTCs
#create function to use for both counties and tracts
any_HTC_sum_function <- function(df) {
  df %>% 
    as.data.frame() %>% 
    select(-total_popE, -unweighted_sample_count_of_popE, -NAME) %>% 
    mutate(any_HTC = rowSums(select(., ends_with("E")))) %>% 
    select(GEOID, any_HTC) %>% 
    left_join(df, by = c("GEOID")) %>% 
    select(GEOID, NAME, total_popE, everything()) %>% 
    st_sf(sf_column_name = "geometry")
}

#apply function
ACS_2018_variables_tract_clean <- any_HTC_sum_function(ACS_2018_variables_tract_clean)
ACS_2018_variables_county_clean <- any_HTC_sum_function(ACS_2018_variables_county_clean)

#create pct HTC category
ACS_2018_variables_tract_clean <- ACS_2018_variables_tract_clean %>% 
  mutate(pct_any_HTC = any_HTC / total_popE)

ACS_2018_variables_county_clean <- ACS_2018_variables_county_clean %>% 
  mutate(pct_any_HTC = any_HTC / total_popE)


```

```{r Calculate HTC percent figures}
#define function to calculate percent figures
calculate_HTC_percentages_function <- function(df) {
  df %>% 
   mutate(pct_foreign_born_entered_US_after_2010E = foreign_born_entered_US_after_2010E / total_popE,
         pct_seniorsE = seniorsE / total_popE,
         pct_black_or_african_americanE = black_or_african_americanE / total_popE,
         pct_american_indian_and_alaska_nativeE = american_indian_and_alaska_nativeE / total_popE,
         pct_asian_american_chinese_or_taiwanese_aloneE = asian_american_chinese_or_taiwanese_aloneE / total_popE,
         pct_asian_american_filipino_aloneE = asian_american_filipino_aloneE / total_popE,
         pct_asian_american_indian_and_subcontinent_aloneE = asian_american_indian_and_subcontinent_aloneE / total_popE,
         pct_asian_american_korean_aloneE = asian_american_korean_aloneE / total_popE,
         pct_asian_american_vietnamese_aloneE = asian_american_vietnamese_aloneE / total_popE,
         pct_children_under_5E = children_under_5E / total_popE,
         pct_have_disabilityE = have_disabilityE / total_popE,
         pct_college_studentsE = college_studentsE / total_popE,
         pct_hispanic_or_latinoE = hispanic_or_latinoE / total_popE,
         pct_have_disabilityE = have_disabilityE / total_popE,
         pct_college_studentsE = college_studentsE / total_popE,
         pct_hispanic_or_latinoE = hispanic_or_latinoE / total_popE,
         pct_rentersE = rentersE / total_popE,
         pct_MENA_originE = MENA_originE / total_popE,
         pct_vacant_housing_for_migrant_workersE = vacant_housing_for_migrant_workersE / total_popE,
         pct_veteran_statusE = veteran_statusE / total_popE,
         pct_native_hawaiian_or_API_aloneE = native_hawaiian_or_API_aloneE / total_popE,
         pct_russian_ancestryE = russian_ancestryE / total_popE
  )
}

#apply function to create percentage calculations
ACS_2018_variables_tract_clean <- calculate_HTC_percentages_function(ACS_2018_variables_tract_clean)
ACS_2018_variables_county_clean <- calculate_HTC_percentages_function(ACS_2018_variables_county_clean)
```

```{r Create summary stats}
#calculate total number of each population in WA
summary_of_all_HTCs_tract <- ACS_2018_variables_tract_clean %>% 
  as.data.frame() %>% 
  select(ends_with("E"), -NAME, -unweighted_sample_count_of_popE, -geometry, -starts_with("pct")) %>% 
  colSums() %>% 
  as.data.frame() %>% 
  rownames_to_column()
colnames(summary_of_all_HTCs_tract)[1] <- "HTC"
colnames(summary_of_all_HTCs_tract)[2] <- "pop"

#calculate total percent of state pop, save as spreadsheet
state_pop <- summary_of_all_HTCs_tract$pop[1] %>% as.numeric
summary_of_all_HTCs_tract <- summary_of_all_HTCs_tract %>% 
  mutate(pct_state = pop / state_pop) %>% 
  write.csv("Summary_stats/total_HTC_pops.csv")

#calculate 5 most populous tracts for each HTC
ACS_2018_variables_tract_clean %>% 
  as.data.frame() %>% 
  select(ends_with("E"), -NAME, -unweighted_sample_count_of_popE, -geometry, -starts_with("pct")) %>% 
  gather(measure, values) %>%
  group_by(measure) %>%
  summarise(data = list(values)) %>%
  rowwise() %>%
  mutate(data = list(data[rev(order(data))][1:3])) %>%
  unnest(data) %>%
  mutate(top = rep(c("top_1", "top_2", "top_3"), length.out = nrow(.))) %>%
  spread(top, data)

```



```{r Create maps}
#erase water in King County
st_erase <- function(x, y) {
  st_difference(x, st_union(y))
}
KC_water <- tigris::area_water("WA", "King", class = "sf")
ACS_2018_variables_tract_clean <- ACS_2018_variables_tract_clean %>%
  st_erase(KC_water)
ACS_2018_variables_county_clean <- ACS_2018_variables_county_clean %>% 
  st_erase(KC_water)

#test plots to help develop function
ACS_2018_variables_county_clean %>%
    ggplot(aes_string(fill = "pct_rentersE")) + 
    geom_sf(color = NA) +
    #{if(zoom_on_KC == TRUE) coord_sf(xlim = c(-122.43, -121.18), ylim = c(47.15, 47.77))} +
    #{if(zoom_on_Seattle == TRUE) coord_sf(xlim = c(-122.5, -122.248), ylim = c(47.495, 47.74))} +
    theme(legend.position = "bottom") +
    ggtitle(paste("Map of", "pct_rentersE")) +
    theme_void() +
    scale_fill_viridis_c(option = "viridis")

#create ggplot uniform map format function. 
  #-has two zoom options: zoom_on_KC for King County, and zoom_on_Seattle for Seattle
ggplot_unform_map_format_function <- function(df, variable, zoom_on_KC = FALSE, zoom_on_Seattle = FALSE) {
  df %>%
    ggplot(aes_string(fill = variable)) + 
    geom_sf(color = NA) +
    {if(zoom_on_KC == TRUE) coord_sf(xlim = c(-122.43, -121.18), ylim = c(47.15, 47.77))} +
    {if(zoom_on_Seattle == TRUE) coord_sf(xlim = c(-122.5, -122.248), ylim = c(47.495, 47.74))} +
    ggtitle(variable) +
    theme_void() +
    scale_fill_viridis_c(option = "viridis", name = "") +
    theme(legend.position = "none")
}

#test function
ggplot_unform_map_format_function(ACS_2018_variables_county_clean, "pct_rentersE")


#create list of variables needed to create plots for
variables_to_plot_list <- colnames(ACS_2018_variables_county_clean[endsWith(colnames(ACS_2018_variables_county_clean), "E")])
variables_to_plot_list <- variables_to_plot_list[-c(1:3)]
variables_to_plot_list <- variables_to_plot_list[-length(variables_to_plot_list)]
variable_plot_length <- length(variables_to_plot_list)

list_of_variables_for_maps <- data.frame("id" = 1:(variable_plot_length),
                                         "variable_to_plot" = c(variables_to_plot_list
                                                               ),
                                         stringsAsFactors = FALSE)


#create all plots
map_list_tract = list()
for(i in 1:variable_plot_length){
  p <- ggplot_unform_map_format_function(ACS_2018_variables_tract_clean, list_of_variables_for_maps$variable_to_plot[i])
  map_list_tract[[i]] <- p
}
map_list_county = list()
for(i in 1:variable_plot_length){
  p <- ggplot_unform_map_format_function(ACS_2018_variables_tract_clean, list_of_variables_for_maps$variable_to_plot[i])
  map_list_county[[i]] <- p
}

#save all plots as jpgs
for(i in 1:length(map_list_tract)){
  ggsave(map_list_tract[[i]], file=paste0("Maps/tract_plot_", list_of_variables_for_maps$variable_to_plot[i],".jpg"), width = 14, height = 5, units = "cm")
}
for(i in 1:length(map_list_county)){
  ggsave(map_list_county[[i]], file=paste0("Maps/county_plot_", list_of_variables_for_maps$variable_to_plot[i],".jpg"), width = 14, height = 5, units = "cm")
}

```

```{r Test Mapview package}
library(mapview)

mapview(ACS_2018_variables_tract_clean, zcol = "pct_any_HTC")


```

